<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ocelot" Version="24.1.0" />
    <PackageReference Include="Ocelot.Cache.CacheManager" Version="24.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DemoECommerce.Shared.LibrarySolution\ecommerce.SharedLibrary\ecommerce.SharedLibrary.csproj" />
  </ItemGroup>

</Project>
